import deepmerge from 'deepmerge'
import {ubl} from './ubl'
import {harvard} from './harvard'
import {nga} from './nga'
import {yale} from './yale'
import {ec} from './ecodices'
import {ox} from './ox'
import {mdz} from './mdz'
import {uc} from './uc'
export const discovery = deepmerge.all([mdz, ox, ubl, uc, harvard, nga, yale, ec])
